name: My First Workflow

on: [push, fork]

jobs:
    first_job:
        runs-on: windows-latest
        steps:
            - name: Welcome message
              run: echo "My First Github Aztions Jobs"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md

